[[constraint]]
  name = "github.com/drone/drone-go"
  revision = "eaa41f7836a191224ec5702d2458db07882ec269"

[[constraint]]
  branch = "master"
  name = "github.com/containership/go-containership.cloud"

[prune]
  go-tests = true
  unused-packages = true
